
Vagrant.configure("2") do |config|

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.hostname = "pasta"
  config.vm.network :forwarded_port, guest: 80, host: 8080  # web
  config.vm.network :forwarded_port, guest: 5984, host: 5984  # couchdb
  config.vm.network :public_network, :bridge => "en0: Ethernet"

  config.vm.synced_folder "..", "/opt/pasta"

  # config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.module_path = "puppet/modules"
    puppet.manifest_file = "webserver.pp"
  end

end
